### ISSUE TITLE
Quick Documentation Request: template-inputs-BAM.yaml with more than one sample so I can test if there's an issue

### ISSUE THREAD

**Issue by Alfredo-Enrique** [uclahs-cds/metapipeline-DNA#38]
**Describe the issue**
Unsure if this is an issue or if I just messed up the input format. Tried running the metapipeline with a single donor, tumor normal pair but it errored out with "input CSV does not follow the format for either BAM or FASTQ inputs". I'm guessing the formatting of my yaml is off. At least I hope that's the case. **Could I get an example of an input format for  a tumor normal sample to test?** 

## The template specifies this format:
```
---
input:
  BAM:
    - patient: "patient ID"
      sample: "sample ID"
      state: "state - normal or tumor"
      path: "/path/to/BAM"
```

I used this:
---
```
input:
  BAM:
    - patient: "DO52564"
      sample: "SA541946"
      state: "tumor"
      path: "/hot/user/alfgonzalez/data/data-SARC-ICGC-BOCA-UK/ade444e6-3414-5530-841c-38d956802b4f/5b9fdbbabb2e1856a80b571147e503c9.bam"
    - patient: "DO52564"
      sample: "SA541947"
      state: "normal"
      path: "/hot/user/alfgonzalez/data/data-SARC-ICGC-BOCA-UK/70432e2c-88f9-5870-9543-899fff998d93/368dbc1d6bafe7ff0fba385888821b89.bam"
```

Error: input CSV does not follow the format for either BAM or FASTQ inputs

- Pipeline release version: 1.00rc1 (https://github.com/uclahs-cds/metapipeline-DNA/commit/7a2597ac4bc82b0ae8834d18b6aad1d5b5b41799)
- Cluster you are using (SGE/Slurm-Dev/Slurm-Test): Slurm
- Node type (F2s (lowmem) / F72s (midmem) / M64s (execute)): Launching on F2 to run on F72
- Submission method (interactive/submission script): Manual lunch "Nextflow run main.nf -c config/template_meta-lead.config'
- Config files : template-config
- input.csv: /hot/user/alfgonzalez/pipeline/metapipeline-DNA/metapipeline-DNA_220716_7a2597a/inputs/template-inputs-BAM.yaml
